### PR TITLE
fix(eventhub): handle required properties

### LINKED ISSUE #76: Azure EventHub Consume and Trigger task: checkpointStoreProperties marked as not required, but the task fails if this attribute is not present
### Expected Behavior

For Azure EventHub Consume and Trigger task, checkpointStoreProperties should either be a required field, OR if it marked not required, then the task should succeed when this property is absent.

### Actual Behaviour

When checkpointStoreProperties is not provided, we get the following error:

```
2024-03-25 15:23:51.395 Invalid URL format. URL: null
2024-03-25 15:23:51.395 Cannot invoke "String.length()" because "<parameter2>" is null
Cannot invoke "String.length()" because "<parameter2>" is null
2024-03-25 15:23:51.395 java.lang.IllegalArgumentException: Invalid URL format. URL: null
	at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:349)
	at com.azure.storage.blob.implementation.util.BuilderHelper.httpsValidation(BuilderHelper.java:188)
	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:119)
	at com.azure.storage.blob.BlobContainerClientBuilder.buildAsyncClient(BlobContainerClientBuilder.java:163)
	at io.kestra.plugin.azure.eventhubs.client.EventHubClientFactory.createBlobContainerAsyncClient(EventHubClientFactory.java:146)
	at io.kestra.plugin.azure.eventhubs.Consume.getBlobCheckpointStore(Consume.java:217)
	at io.kestra.plugin.azure.eventhubs.Consume.run(Consume.java:141)
	at io.kestra.plugin.azure.eventhubs.Consume.run(Consume.java:117)
	at io.kestra.plugin.azure.eventhubs.Consume.run(Consume.java:48)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:710)
Caused by: java.net.MalformedURLException: Cannot invoke "String.length()" because "<parameter2>" is null
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:347)
	... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter2>" is null
	... 13 more
```

### Steps To Reproduce

1. Run the flow provided in the Example Flow. (Ensure you do not add `checkpointStoreProperties` property)
2. Check the logs on executing this flow.

### Environment Information

- Kestra Version: 0.15.5
- Plugin version: 0.15.5
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```
id: ConsumeDataEventsFromAzureEventHubs
namespace: company.team
tasks:
- id: consumeFromEventHubs
  type: io.kestra.plugin.azure.eventhubs.Consume
  eventHubName: <event-name>
  namespace: <eventhub-namespace>
  connectionString: "<connectionString>"
  bodyDeserializer: STRING
  consumerGroup: "$Default"
```

### PR DESCRIPTION
**Pull request by Malaydewangan09**
closes #76

### CODE REVIEW

File: src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java [hunk 1]
```diff
@@ -105,8 +106,8 @@ public class Trigger extends AbstractTrigger implements EventHubConsumerInterfac
     @Builder.Default
     private Property<Duration> maxDuration = Property.ofValue(Duration.ofSeconds(10));
 
-    @Builder.Default
-    private Property<Map<String, String>> checkpointStoreProperties = Property.ofValue(new HashMap<>());
+    @NotNull
+    private Property<Map<String, String>> checkpointStoreProperties;
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java:110]: No error message will be trigger for this one?

**Review by fdelbrayelle — APPROVED** [review]

File: src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java (hunk 1 above)
Comment (Malaydewangan09) [reply src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java:110]: Already added custom error messages when fields are missing.
